# Generated by Django 4.1.6 on 2023-02-02 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_code', models.IntegerField(max_length=6)),
                ('confirmation', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('tc_no', models.IntegerField(max_length=11)),
                ('birth_date', models.IntegerField(max_length=40)),
                ('tel_no', models.IntegerField(max_length=40)),
                ('confirmation', models.BooleanField()),
                ('email', models.CharField(max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uygulama.sms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uygulama.user')),
            ],
        ),
    ]
