# Generated by Django 4.1.6 on 2023-02-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel_no',
            field=models.IntegerField(),
        ),
    ]
