# Generated by Django 4.1.6 on 2023-02-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0002_alter_user_birth_date_alter_user_tel_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='sms_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='tc_no',
            field=models.IntegerField(),
        ),
    ]
