# Generated by Django 4.1.6 on 2023-02-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0003_alter_sms_sms_code_alter_user_tc_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='sms_code',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='tc_no',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel_no',
            field=models.CharField(max_length=10),
        ),
    ]
