# Generated by Django 4.1.6 on 2023-02-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0004_alter_sms_sms_code_alter_user_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='ip_tables',
            field=models.CharField(default='iptables ayarları', max_length=40),
        ),
    ]
