# Generated by Django 4.1.6 on 2023-02-14 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0005_log_ip_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_code', models.CharField(max_length=6)),
                ('confirmation', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uygulama.user')),
            ],
        ),
    ]
