# Generated by Django 4.1.6 on 2023-02-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0006_email_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel_no',
            field=models.CharField(max_length=11),
        ),
    ]
