# Generated by Django 4.1.6 on 2023-02-14 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0007_alter_user_tel_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='email_ver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uygulama.email_verification'),
        ),
    ]
