# Generated by Django 4.1.6 on 2023-02-17 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0010_alter_email_verification_options_alter_log_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_verification',
            name='user',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='uygulama.user'),
        ),
        migrations.AlterField(
            model_name='log',
            name='email_ver',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='uygulama.email_verification'),
        ),
        migrations.AlterField(
            model_name='log',
            name='ip_tables',
            field=models.CharField(default='null', max_length=40),
        ),
        migrations.AlterField(
            model_name='log',
            name='sms',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='uygulama.sms'),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='uygulama.user'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='sms_code',
            field=models.CharField(default='null', max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.CharField(default='null', max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='null', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='null', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(default='null', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='tc_no',
            field=models.CharField(default='null', max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel_no',
            field=models.CharField(default='null', max_length=11),
        ),
    ]
